### ISSUE TITLE
Package cannot find necessary dependencies

### ISSUE THREAD

**Issue by ahartman** [IBM-Swift/iOSSampleKituraKit#6]
The ToDoServer in this package no longer builds, not finding dependencies:
KituraNet and KituraTemplateEngine.

Please see attached end Swift build output.

[KituraKit build output.txt](https://github.com/IBM-Swift/iOSSampleKituraKit/files/1825687/KituraKit.build.output.txt)

I am dependent on this example in starting a new project and do not know how to resolve this myself.
All help much appreciated.
Kind regards, André Hartman, Belgium

**Comment by sandmman** [comment]
@ahartman What OS and which version of swift are you using?

It looks like this isn't a clean project either. Have you tried deleting your Package.resolved and recompiling?

**Comment by ahartman** [comment]
Dear sandmman,
The project was a clean clone of
[KituraKit build output.txt](https://github.com/IBM-Swift/iOSSampleKituraKit/files/1826409/KituraKit.build.output.txt)
[KituraKit build output.txt](https://github.com/IBM-Swift/iOSSampleKituraKit/files/1826412/KituraKit.build.output.txt)

 GitHub; I did it again as you can see in attached build output.
I am using OS 10.13.3 and Swift 4.1 (Apple Swift version 4.1-dev (LLVM 1c8b50929b, Clang 420ae40df6, Swift 4ebcde867a)

Kind regards, André Hartman

**Comment by ShihabMehboob** [comment]
@ahartman May I suggest switching to Swift 4.0.3 as Swift 4.1 isn't yet out, and isn't entirely supported just yet.

If you'd like to do this via Xcode, head over to the menu bar at the top, Xcode > Toolchains > and select a previous Swift version, preferably Swift 4.0.3, which you could download [here](https://swift.org/builds/swift-4.0.3-release/xcode/swift-4.0.3-RELEASE/swift-4.0.3-RELEASE-osx.pkg) if you haven't got it. This should help resolve most of the issues regarding deprecations.

**Comment by ahartman** [comment]
Sorry to trouble you on this again.
I followed your advice, went back to 4.0.3, problem persists.
==============
'Kitura' /Users/gebruiker/Desktop/iOSSampleKituraKit-master/ToDoServer/.build/checkouts/Kitura.git-6522211175291160341: error: product dependency 'KituraNet' not found
'Kitura' /Users/gebruiker/Desktop/iOSSampleKituraKit-master/ToDoServer/.build/checkouts/Kitura.git-6522211175291160341: error: product dependency 'KituraTemplateEngine' not found
====================
Could this be a writing error in Package.swift?
I find references on Internet to KituraNet as well as Kitura-Net, the same for KituraTemplateEngine.
Kind regards, André Hartman

**Comment by ShihabMehboob** [comment]
@ahartman Could you paste here what your Package.swift file looks like please? There may have been a mismatch or typo in that file where it cannot find KituraNet and KituraTemplateEngine.

**Comment by stonedauwg** [comment]
Seeing same problem. Simply cloned this repo, followed instructions in readme and get the errors when running swift build from command line under ToDoServer folder

**Comment by ahartman** [comment]
no longer using kitura
